name: Build Docker Image

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
      security-events: write
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash
            
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
  
      - uses: d4rkfella/actions/apko-snapshot@81b2939a844bf668bfee497b3a491c6a5cc1ae1e # main
        id: apko
        with:
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
          additional-tags: 1.0.0
          archs: amd64
          slsa-attest: "true"
          sbom-attest: "true"
          build-repository-append: https://packages.darkfellanetwork.com
          keyring-append: https://packages.darkfellanetwork.com/melange.rsa.pub
  
      - uses: d4rkfella/actions/vul-scans@main
        id: scans
        with:
          RUN_SNYK: false
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.apko.outputs.digest }}
          UPLOAD_GITHUB_CODE: true
